Домашнее задание 3 - Графика
htmlacademy-htmlcss/1130549-sedona-30 pull request #4
Opened 2021-02-01 15:44 UTC by maria-klonova

2021-02-01 17:19 UTC, mikhin commented on catalog.html
> +          <li>Гостиницы</li>
Здесь нужен все-равно какой-то элемент, т.к. в дальнейшем, скорее всего, почти вся стилизация этих пунктов меню ляжет именно на этот элемент. Пока что это ссылка, но если ссылка по какой-то причине не подходит, например, потому что мы уже находимся на этой странице, то можно поставить span.

2021-02-01 17:23 UTC, mikhin requested changes
@maria-klonova, касается почти всех имен файлов изображений. Давай все назовем классно — понятно и читабельно. Чтобы уже даже по одному названию было более-менее понятно, что это за файл и для чего нужен, и не нужно его было открывать для понимания)

2021-02-01 17:23 UTC, mikhin commented on catalog.html
> +              <div></div>
Пока непонятно зачем нужен этот див)

2021-02-01 17:23 UTC, mikhin commented on catalog.html
> +            src="img/Layer 21.jpg"
В разработке, в широком смысле слова, пробелы никогда не должны использоваться в именах файлов. Плюс ко всему все сущности, в том числе имена файлов, должны быть названы аккуратно и осмысленно, чтобы проект был понятным и легко считывался для тебя самой, через год например, или для твоих коллег. Давай переименуем?)

2021-02-01 17:23 UTC, mikhin commented on css/style.css
> +.stars {
Стилизацию пока не смотрю, гляну в следующем ДЗ, про стилизацию)

2021-02-02 16:32 UTC, mikhin requested changes

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +  width: 100%;
В данном случае, если указан max-width, то width 100% может можно и не указывать?)

2021-02-02 16:32 UTC, mikhin commented on css/style.css
>    font-weight: 700;
Обычно на body вешается минимальное количество стилей, чтобы в дальнейшем не пришлось их переопределять на всех классах. Так вот font-weight 700 это действительно базовый стиль для всего документа?)

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +  margin-left: auto;
margin: 0 auto; =)

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +  height: 509px;
Высота редко используется на контентных блоках, потому что количество контента может измениться и тогда верстка поедет. Например текста может стать в два раза больше, верстка должна быть к этому готова =)

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +  background-position-x: center;
background-position: center bottom; =)

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +.city-description__title {
Пустые классы давай пока удалим?)

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +.features-list__item {
О, а ты решила-таки по БЭМ классы именовать?) Это круто и похвально!

2021-02-02 16:32 UTC, mikhin commented on css/style.css
> +  background-position: center, 0 0;
А зачем два значения?

2021-02-02 16:32 UTC, mikhin commented on index.html
> +          <h2>Причины</h2>
В идеале классы должны быть на всех элементах в HTML — это улучшает качество исходного кода: код становится более читабельным и понятным, интерфейс начинает считываться даже из HTML)

2021-02-02 16:32 UTC, mikhin commented on index.html
> +                  <i class="subfeatures__icon subfeatures__icon--home"></i>
Все неконтентные изображения, интерфейсные, за которыми не пришел пользователь и которые не дают контентной пользы пользователю — во-первых должны быть убраны в CSS, а во-вторых не должны висеть в HTML. Потому что украшения — это зона ответственности CSS, а HTML — он про содержание и структуру документа)

2021-02-02 16:32 UTC, mikhin commented on index.html
> +                    +
Вместо этих обозначений сюда лучше добавить осмысленный понятный текст, который бы описывал и объяснял действие контрола. Это поможет поисковым системам и всяким читалкам лучше понимать документ. А плюсики и минусики можно оформить псевдоэлементами в CSS)

2021-02-02 16:32 UTC, mikhin commented on index.html
> +              src="https://via.placeholder.com/1200x594"
А здесь нужна тоже картинка в рамках этого ДЗ?

2021-02-10 08:06 UTC, mikhin requested changes

2021-02-10 08:06 UTC, mikhin commented on css/style.css
> +.button {
Если этот класс может висеть и на ссылках и на кнопках, то ему нужно еще добавить background transparent, т.к. по умолчанию кнопки в браузерах имеют цвет

2021-02-10 08:06 UTC, mikhin commented on css/style.css
> +.site-navigation__item span {
чисто по опыту скажу что лучше никогда не стилизовать селекторы тегов а всегда использовать классы ;) но сейчас можем забить

2021-02-10 08:06 UTC, mikhin commented on img/Shape (1).svg
> +<svg width="458" height="214" viewBox="0 0 458 214" fill="none" xmlns="http://www.w3.org/2000/svg">
В именах файлов не должно быть скобок и пробелов

2021-02-10 08:06 UTC, mikhin commented on img/Shape (2).svg
> +<svg width="189" height="46" viewBox="0 0 189 46" fill="none" xmlns="http://www.w3.org/2000/svg">
В именах файлов не должно быть скобок и пробелов

2021-02-10 08:06 UTC, mikhin commented on img/Shape (3).svg
> +<svg width="256" height="29" viewBox="0 0 256 29" fill="none" xmlns="http://www.w3.org/2000/svg">
В именах файлов не должно быть скобок и пробелов

2021-02-10 08:06 UTC, mikhin commented on img/Shape (1).svg
> +<svg width="458" height="214" viewBox="0 0 458 214" fill="none" xmlns="http://www.w3.org/2000/svg">
Плюс какое-то понятное имя файла нужно)

2021-02-10 08:06 UTC, mikhin commented on img/Shape (2).svg
> +<svg width="189" height="46" viewBox="0 0 189 46" fill="none" xmlns="http://www.w3.org/2000/svg">
Плюс какое-то понятное имя файла нужно)

2021-02-10 08:06 UTC, mikhin commented on img/Shape (3).svg
> +<svg width="256" height="29" viewBox="0 0 256 29" fill="none" xmlns="http://www.w3.org/2000/svg">
Плюс какое-то понятное имя файла нужно)

2021-02-10 08:06 UTC, mikhin commented on index.html
> +          <p class="features__title">
Класс подсказывает что это не просто абзац

2021-02-10 08:06 UTC, mikhin commented on index.html
> +          <h2 class="visually-hidden">Причины</h2>
Если есть настоящий заголовок (ниже) то скрытый уже не нужен)

2021-02-10 08:06 UTC, mikhin commented on index.html
> +                  <i class="subfeatures__icon subfeatures__icon--burger"></i>
А почему тут тег i использован?) Можешь рассказать чутка?)

2021-02-10 08:06 UTC, mikhin commented on index.html
> +          <p class="hotel-search__title">Заинтересовались?</p>
Класс намекает что это заголовок)

2021-02-10 08:06 UTC, mikhin commented on index.html
> +              src="https://via.placeholder.com/1200x594"
Так нужна картинка или нет?)

2021-02-10 11:41 UTC, maria-klonova commented on catalog.html
> +          <li>Гостиницы</li>
поставила span

2021-02-10 11:42 UTC, maria-klonova commented on catalog.html
> +              <div></div>
убрала

2021-02-10 11:42 UTC, maria-klonova commented on catalog.html
> +            src="img/Layer 21.jpg"
исправила

2021-02-10 11:42 UTC, maria-klonova commented on css/style.css
> +.stars {
+

2021-02-10 11:43 UTC, maria-klonova commented on css/style.css
> +  width: 100%;
изменила

2021-02-10 11:43 UTC, maria-klonova commented on css/style.css
>    font-weight: 700;
исправила на 400

2021-02-10 11:43 UTC, mikhin commented on css/style.css
> +.stars {
уже посмотрел)

2021-02-10 11:44 UTC, maria-klonova commented on css/style.css
> +  margin-left: auto;
сделала

2021-02-10 11:44 UTC, maria-klonova commented on css/style.css
> +  height: 509px;
исправила

2021-02-10 11:44 UTC, maria-klonova commented on css/style.css
> +  background-position-x: center;
исправила

2021-02-10 11:45 UTC, maria-klonova commented on css/style.css
> +  background-position: center, 0 0;
исправила

2021-02-10 11:45 UTC, maria-klonova commented on index.html
> +          <h2>Причины</h2>
исправила добавила везде

2021-02-10 11:46 UTC, maria-klonova commented on index.html
> +                  <i class="subfeatures__icon subfeatures__icon--home"></i>
убрала

2021-02-11 06:16 UTC, maria-klonova commented on index.html
> +                    +
исправила

2021-02-11 06:16 UTC, maria-klonova commented on index.html
> +              src="https://via.placeholder.com/1200x594"
убрала

2021-02-11 08:34 UTC, maria-klonova commented on catalog.html
> +                  <label class="catalog-form__label" for="filter-pool">
удалила

2021-02-11 08:34 UTC, maria-klonova commented on catalog.html
> +              <a class="ordering__link"><span>По цене</span></a>
исправила

2021-02-11 08:34 UTC, maria-klonova commented on catalog.html
> +          <span class="ordering__results-count">Найдено: 3</span>
сделала

2021-02-11 08:36 UTC, maria-klonova commented on catalog.html
> +                <div class="stars stars--4"></div>
Как грамотно сделать эти звездочки?

2021-02-11 08:36 UTC, maria-klonova commented on css/style.css
> +  font-weight: 400;
да, ок. убрала

2021-02-11 08:38 UTC, maria-klonova commented on css/style.css
> +  background-color: #f2f2f2;
да

2021-02-11 08:39 UTC, maria-klonova commented on css/style.css
> +  background-color: var(--basic-white);
сделала серую подложку, сверху белый. Понимаю, что по секциям цвет назначать нужно.  Но весь сайт белый, поэтому и подумала поставить белый

2021-02-11 08:40 UTC, maria-klonova commented on css/style.css
> +.button {
сделала

2021-02-11 08:41 UTC, maria-klonova commented on css/style.css
> +.site-navigation__item span {
сделала. забивать нельзя))))

2021-02-11 08:41 UTC, maria-klonova commented on img/Shape (1).svg
> +<svg width="458" height="214" viewBox="0 0 458 214" fill="none" xmlns="http://www.w3.org/2000/svg">
удалила неиспользуемую картинку

2021-02-11 08:42 UTC, maria-klonova commented on img/Shape (2).svg
> +<svg width="189" height="46" viewBox="0 0 189 46" fill="none" xmlns="http://www.w3.org/2000/svg">
удалила неиспользуемую картинку

2021-02-11 08:42 UTC, maria-klonova commented on img/Shape (3).svg
> +<svg width="256" height="29" viewBox="0 0 256 29" fill="none" xmlns="http://www.w3.org/2000/svg">
удалила неиспользуемую картинку

2021-02-11 08:45 UTC, maria-klonova commented on index.html
> +          <h2 class="visually-hidden">Причины</h2>
Это отдельная секция. И далее идет список со своими заголовками

2021-02-11 08:47 UTC, maria-klonova commented on index.html
> +                  <i class="subfeatures__icon subfeatures__icon--burger"></i>
загуглила). Изменила

2021-02-11 08:49 UTC, maria-klonova commented on index.html
> +          <p class="hotel-search__title">Заинтересовались?</p>
изменила

2021-02-11 08:53 UTC, maria-klonova commented on index.html
> +          <p class="features__title">
изменила

2021-02-11 17:27 UTC, mikhin commented on index.html
> +                  <i class="subfeatures__icon subfeatures__icon--burger"></i>
А что изменила? Вроде бы сейчас тег i так и остался?

2021-02-11 17:27 UTC, mikhin commented on index.html
> +          <p class="hotel-search__title">Заинтересовались?</p>
А что изменила? Вижу что сейчас абзац так и остался)

2021-02-11 17:28 UTC, mikhin commented on index.html
> +          <p class="features__title">
А что изменила? Вижу что сейчас это абзац по прежнему)

2021-02-11 17:30 UTC, mikhin commented on catalog.html
> +                <div class="stars stars--4"></div>
Ну прям разметку полностью. Что это может быть? Наверно это список кнопок просто? Ведь пользователь по идее должен мочь суметь нажать на каждую, чтобы выставить рейтинг?

2021-02-12 05:54 UTC, merged